// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyxnodxivcayprdraryc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5eG5vZHhpdmNheXByZHJhcnljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzMzk4MzgsImV4cCI6MjA4NDkxNTgzOH0.7thccbqDCOHyGChi6zJ4qHNrGMnvwIQGIPK5_n-cZ3c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});